
export default function Head() {
  return (
    <>
      <title>M-catering app</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      <link rel="alternate icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" sizes="180x180" href="/favicon.png" />
    </>
  );
}
